name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: super-linter/super-linter@v4
        with:
          linters:
            - flake8
            - pylint
          extensions:
            - py